name = "ns-theatre"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[[pages_build_output_dir]]
output_dir = ".vercel/output/static"
